import { Link, useLocation } from "wouter";
import { useState, useEffect } from "react";
import {
  LayoutDashboard, Users, CalendarCheck, ClipboardList,
  Trophy, Settings, MapPin, BedDouble,
  BarChart2, PhoneForwarded, LogOut, ScrollText, TrendingUp, MessageCircle, MessagesSquare, ShieldCheck,
  FileText, PlayCircle, Smartphone, BarChart, LifeBuoy, Video, PhoneCall, BookOpen, Plane, Webhook, Plug, UserCheck, PhoneIncoming, Upload, Inbox, Clock, ChevronDown, ChevronRight, Settings2,
} from "lucide-react";
import { useQuery } from "@tanstack/react-query";
import { Badge } from "@/components/ui/badge";
import {
  Sidebar, SidebarContent, SidebarGroup, SidebarGroupContent,
  SidebarGroupLabel, SidebarMenu, SidebarMenuButton, SidebarMenuItem,
  SidebarHeader, SidebarFooter, useSidebar,
} from "@/components/ui/sidebar";
import { HoverCard, HoverCardContent, HoverCardTrigger } from "@/components/ui/hover-card";
import { useAuth } from "@/lib/auth";

// ── Nav structure ────────────────────────────────────────────────────────────

interface NavItem {
  title: string;
  url: string;
  icon: any;
  badge?: string;
  help?: { summary: string; features: string[] };
}

const help = {
  dashboard: {
    summary: "Your personal home base. See today's performance at a glance and track your weekly progress.",
    features: [
      "Today's call stats (transfers, appointments, fell throughs)",
      "Weekly goal progress bars for calls, transfers, and appointments",
      "Upcoming appointments sorted by time",
      "Daily LO assignments and recent activity",
    ],
  },
  myReport: {
    summary: "A detailed breakdown of your personal call history and performance metrics.",
    features: [
      "Filter by date range to see any time period",
      "Full outcome breakdown (transfers, appointments, callbacks, etc.)",
      "Weekly comparison showing your stats day by day",
      "Goal vs actual tracking per metric",
    ],
  },
  directory: {
    summary: "The complete list of Loan Officers your team works with.",
    features: [
      "View all LOs with contact info, NMLS ID, and status",
      "See how recently each LO has been worked",
      "Admin: add, edit, or deactivate LOs",
      "Track LO availability and vacation/status settings",
    ],
  },
  assignments: {
    summary: "Today's LO calling list, generated by the smart assignment algorithm.",
    features: [
      "Daily assignments generated once per day and locked until tomorrow",
      "Algorithm weights recency, frequency, availability, transfers, and priority tier",
      "Admin: generate assignments and view the full team's list",
      "CLRs see only their own assigned LOs for the day",
    ],
  },
  stats: {
    summary: "The team leaderboard showing performance across all CLRs.",
    features: [
      "Switch between Daily, Weekly, and All-Time views",
      "See calls, transfers, appointments, fell throughs, and more per CLR",
      "\"vs Goal\" column shows progress against individual targets",
      "Sortable by any metric",
    ],
  },
  chat: {
    summary: "Real-time team chat for quick communication.",
    features: [
      "Send messages to the whole team instantly",
      "Visible to all users in your organization",
      "Scroll back through message history",
    ],
  },
  forum: {
    summary: "A Q&A discussion board for the team.",
    features: [
      "Post questions and get answers from teammates or admins",
      "Upvote helpful answers and mark accepted solutions",
      "Admins can pin important posts",
      "Subscribe to posts to get notified of new answers",
    ],
  },
  callHistory: {
    summary: "A complete log of every call outcome ever logged.",
    features: [
      "Defaults to your own call history",
      "Admins can view any CLR's history or all users combined",
      "Filter by outcome type, date range, or LO",
      "Edit outcome status after the fact",
    ],
  },
  eodReport: {
    summary: "Submit your end-of-day summary to managers.",
    features: [
      "Auto-saves as a draft as you fill it out",
      "Managers receive a detailed email with your notes and stats",
      "Include additional LOs not in your daily assignment",
      "Draft is restored if you close the page before submitting",
    ],
  },
  appointments: {
    summary: "Manage all your scheduled appointments and callbacks.",
    features: [
      "View upcoming, overdue, and completed appointments",
      "Filter by Appointments, Callbacks, or Deferrals",
      "Complete an appointment as Transfer or Fell Through",
      "Reminders sent via email, SMS, and push notification",
    ],
  },
  loStats: {
    summary: "Performance analytics for each Loan Officer.",
    features: [
      "See transfer history and call volume per LO",
      "90-day transfer trends and timeframe breakdowns",
      "Helps identify which LOs convert best",
    ],
  },
  loVacation: {
    summary: "Manage LO availability so assignments stay accurate.",
    features: [
      "Mark LOs as on vacation, inactive, or unavailable",
      "Unavailable LOs are excluded from daily assignment generation",
      "Admin only",
    ],
  },
  reporting: {
    summary: "Weekly and historical performance reports.",
    features: [
      "View weekly summaries for any past week",
      "Per-CLR stats with full outcome breakdown",
      "Notes from call outcomes included in reports",
    ],
  },
  settings: {
    summary: "Configure your personal preferences and app settings.",
    features: [
      "Update your profile, name, and contact info",
      "Set your calling script name and LO overrides",
      "Toggle email, SMS, and push notification preferences",
      "Admin: manage users, set goals, configure integrations, export data",
    ],
  },
  glossary: {
    summary: "A reference guide to mortgage and CLR industry terms.",
    features: [
      "100+ terms across 6 categories: Mortgage Basics, Loan Types, CLR Operations, Credit, Property/Title, Regulatory",
      "Search across all terms and definitions",
      "Grouped by category with expandable sections",
      "Admin: add, edit, or delete terms",
    ],
  },
  script: {
    summary: "Your personalized cold calling script with smart placeholders.",
    features: [
      "Placeholders like [your name], [lo name], [borrower name] auto-fill as you work",
      "Select today's LO from a dropdown",
      "Start Call mode tracks duration and logs the outcome directly to call history",
      "Admin: edit any CLR's script or the default script for all users",
    ],
  },
} as const;

const mainItems: NavItem[] = [
  { title: "Home",                  url: "/",             icon: LayoutDashboard, help: help.dashboard },
  { title: "Calling Script",        url: "/call-script",  icon: PhoneCall,       help: help.script },
  { title: "State Lookup",          url: "/state-lookup", icon: MapPin },
  { title: "Call Hours",            url: "/call-hours",   icon: Clock },
  { title: "Install App",           url: "/install",      icon: Smartphone },
];

const reportingItems: NavItem[] = [
  { title: "Your Call List",        url: "/assignments",  icon: CalendarCheck,   help: help.assignments },
  { title: "Input Results",         url: "/outcomes",     icon: ClipboardList,   help: help.callHistory },
  { title: "EOD Report",            url: "/eod-report",   icon: FileText,        help: help.eodReport },
  { title: "Upcoming Appointments", url: "/appointments", icon: PhoneForwarded,  badge: "appointments", help: help.appointments },
  { title: "Time Off",              url: "/time-off",     icon: Plane },
  { title: "Install App",           url: "/install",      icon: Smartphone },
];

const teamItems: NavItem[] = [
  { title: "Team Stats",            url: "/leaderboard",  icon: Trophy,          help: help.stats },
  { title: "Forum",                 url: "/forum",        icon: MessagesSquare,  help: help.forum },
  { title: "Chat",                  url: "/chat",         icon: MessageCircle,   badge: "chat", help: help.chat },
];

const toolItems: NavItem[] = [
  { title: "LO Directory",    url: "/directory",      icon: Users,        help: help.directory },
  { title: "LO Stats",        url: "/lo-performance", icon: TrendingUp,   help: help.loStats },
  { title: "LO Vacation",     url: "/snooze",         icon: BedDouble,    help: help.loVacation },
  { title: "Glossary",        url: "/glossary",       icon: BookOpen,     help: help.glossary },
  { title: "NMLS Tracker",    url: "/nmls-checks",    icon: ShieldCheck,  badge: "nmls" },
];

const adminItems: NavItem[] = [
  { title: "My Report",       url: "/my-report",   icon: BarChart2,       help: help.myReport },
  { title: "Report Archive",  url: "/reports-archive", icon: Inbox },
  { title: "Settings",        url: "/settings",    icon: Settings,        help: help.settings },
];

// Viewer accounts get only the Report Archive (read-only role)
const viewerItems: NavItem[] = [
  { title: "Report Archive",  url: "/reports-archive", icon: Inbox },
];

const integrationItems: NavItem[] = [
  { title: "Integrations",    url: "/integrations", icon: Plug },
  { title: "Contact Hub",     url: "/contacts", icon: Users },
  { title: "Bonzo Prospects", url: "/bonzo-prospects", icon: UserCheck },
  { title: "Mojo Sessions",   url: "/mojo-sessions", icon: PhoneIncoming },
  { title: "Mojo Import",     url: "/mojo-import", icon: Upload },
];

// ── Component ────────────────────────────────────────────────────────────────

export function AppSidebar() {
  const [location] = useLocation();
  const { user, logout } = useAuth();

  // Advanced Settings folder — collapsed by default; preference persisted.
  const [advancedOpen, setAdvancedOpen] = useState(() => {
    try { return localStorage.getItem("sidebar.advancedOpen") === "1"; } catch { return false; }
  });
  useEffect(() => {
    try { localStorage.setItem("sidebar.advancedOpen", advancedOpen ? "1" : "0"); } catch {}
  }, [advancedOpen]);

  // Live appointment count — active appointment-type outcomes with followUpDate in the next 3 days.
  // Excludes outcomes that already became transfers or that are overdue (< today).
  // Window is today through today + 3 days (inclusive). Only counts the current
  // user's own appointments — other CLRs' upcoming appointments are private.
  const myUserId = (user as any)?.id ?? null;
  const { data: outcomes = [] } = useQuery<any[]>({
    queryKey: ["/api/outcomes"],
    refetchInterval: 60000,
    select: (data) => {
      const ACTIVE_APPT_TYPES = new Set(["appointment", "callback_requested", "deferral", "future_contact"]);
      const now = new Date();
      const today = new Date(now.getFullYear(), now.getMonth(), now.getDate());
      const cutoff = new Date(today);
      cutoff.setDate(cutoff.getDate() + 3);
      // Local YYYY-MM-DD (avoid toISOString UTC drift)
      const pad = (n: number) => String(n).padStart(2, "0");
      const todayStr = `${today.getFullYear()}-${pad(today.getMonth() + 1)}-${pad(today.getDate())}`;
      const cutoffStr = `${cutoff.getFullYear()}-${pad(cutoff.getMonth() + 1)}-${pad(cutoff.getDate())}`;
      // cutoffEnd lets ISO timestamps on the cutoff day still match ("2026-04-26T10:00:00Z" <= "2026-04-26T23:59:59Z")
      const cutoffEndStr = `${cutoffStr}T23:59:59.999Z`;
      return data.filter((o) => {
        if (!ACTIVE_APPT_TYPES.has(o.outcomeType)) return false;
        // Only count the current user's own upcoming appointments (others' are private)
        if (myUserId != null && o.assistantId !== myUserId) return false;
        const fd: string | null | undefined = o.followUpDate;
        if (!fd) return false;
        // Extract YYYY-MM-DD portion for lower-bound compare; full string for upper-bound
        const dateOnly = fd.slice(0, 10);
        if (dateOnly < todayStr) return false; // overdue
        if (fd > cutoffEndStr) return false; // beyond window
        return true;
      });
    },
  });

  const appointmentCount = outcomes.length;

  // ── Chat unread badge ──────────────────────────────────────────────────────
  const storageKey = `lastSeenChatId_${user?.id ?? "guest"}`;
  const [lastSeenId, setLastSeenId] = useState<number>(() => {
    return parseInt(localStorage.getItem(storageKey) ?? "0") || 0;
  });

  const { data: chatData } = useQuery<{ messages: any[] }>({
    queryKey: ["/api/chat"],
    refetchInterval: 5000,
    enabled: !!user,
  });

  const latestChatId = chatData?.messages?.length
    ? Math.max(...chatData.messages.map((m: any) => m.id))
    : 0;

  const unreadChatCount = chatData?.messages
    ? chatData.messages.filter(
        (m: any) => m.id > lastSeenId && m.user_id !== user?.id
      ).length
    : 0;

  useEffect(() => {
    if (location === "/chat" && latestChatId > 0) {
      setLastSeenId(latestChatId);
      localStorage.setItem(storageKey, String(latestChatId));
    }
  }, [location, latestChatId, storageKey]);

  // ── Helpers ────────────────────────────────────────────────────────────────
  const initials = user
    ? user.name.split(" ").map((n: string) => n[0]).slice(0, 2).join("").toUpperCase()
    : "?";

  const roleLabel = user
    ? user.role.charAt(0).toUpperCase() + user.role.slice(1)
    : "";

  function isActive(url: string) {
    if (url === "/") return location === "/";
    return location.startsWith(url);
  }

  function getBadgeCount(badge?: string) {
    if (badge === "appointments") return appointmentCount;
    if (badge === "chat") return unreadChatCount;
    return 0;
  }

  function renderItems(items: NavItem[]) {
    return items.map((item) => {
      const count = getBadgeCount(item.badge);
      const active = isActive(item.url);
      const link = (
        <Link
          href={item.url}
          data-testid={`nav-${item.title.toLowerCase().replace(/ /g, "-")}`}
          className="flex items-center justify-between w-full"
        >
          <span className="flex items-center gap-2">
            <item.icon className="w-4 h-4 shrink-0" />
            <span className={active ? "font-bold" : ""}>{item.title}</span>
          </span>
          {count > 0 && (
            <Badge className="ml-auto h-4 min-w-4 px-1 text-[10px] bg-destructive text-destructive-foreground">
              {count > 99 ? "99+" : count}
            </Badge>
          )}
        </Link>
      );

      return (
        <SidebarMenuItem key={item.title}>
          {item.help ? (
            <HoverCard openDelay={250} closeDelay={100}>
              <HoverCardTrigger asChild>
                <SidebarMenuButton asChild isActive={active}>
                  {link}
                </SidebarMenuButton>
              </HoverCardTrigger>
              <HoverCardContent
                side="right"
                align="start"
                sideOffset={12}
                className="w-[280px] p-3 text-xs"
              >
                <p className="text-sm font-bold mb-1.5">{item.title}</p>
                <p className="text-muted-foreground leading-snug mb-2">{item.help.summary}</p>
                <ul className="list-disc pl-4 space-y-1 text-muted-foreground leading-snug">
                  {item.help.features.map((f, i) => (
                    <li key={i}>{f}</li>
                  ))}
                </ul>
              </HoverCardContent>
            </HoverCard>
          ) : (
            <SidebarMenuButton asChild isActive={active}>
              {link}
            </SidebarMenuButton>
          )}
        </SidebarMenuItem>
      );
    });
  }

  // ── Render ─────────────────────────────────────────────────────────────────
  const { isMobile, state } = useSidebar();
  const showAdvanced = advancedOpen;

  return (
    <Sidebar collapsible="offcanvas" className="glass-rail [&_[data-sidebar=sidebar]]:bg-transparent [&_[data-sidebar=sidebar]]:border-0">
      <SidebarHeader className="px-3 py-4 border-b border-sidebar-border">
        <img
          src="/logo-menu.svg"
          className="h-9 w-auto self-start pl-1"
          style={{ filter: 'brightness(0) saturate(100%) invert(85%) sepia(28%) saturate(541%) hue-rotate(2deg) brightness(96%) contrast(89%)' }}
          alt="CLR Connection Center"
        />
      </SidebarHeader>

      <SidebarContent>
        {/* MAIN — always visible, never collapsed */}
        <SidebarGroup>
          <SidebarGroupLabel className="text-sidebar-foreground/50 text-xs uppercase tracking-widest">
            Main
          </SidebarGroupLabel>
          <SidebarGroupContent>
            <SidebarMenu>{renderItems(mainItems)}</SidebarMenu>
          </SidebarGroupContent>
        </SidebarGroup>

        {/* REPORTING — always visible */}
        <SidebarGroup>
          <SidebarGroupLabel className="text-sidebar-foreground/50 text-xs uppercase tracking-widest">
            Reporting
          </SidebarGroupLabel>
          <SidebarGroupContent>
            <SidebarMenu>{renderItems(reportingItems)}</SidebarMenu>
          </SidebarGroupContent>
        </SidebarGroup>

        {/* TEAM — always visible */}
        <SidebarGroup>
          <SidebarGroupLabel className="text-sidebar-foreground/50 text-xs uppercase tracking-widest">
            Team
          </SidebarGroupLabel>
          <SidebarGroupContent>
            <SidebarMenu>{renderItems(teamItems)}</SidebarMenu>
          </SidebarGroupContent>
        </SidebarGroup>

        {/* ADVANCED SETTINGS — collapsible folder containing every other group.
           Hidden entirely when the rail is in icon-only mode (the underlying
           groups still render below when advancedOpen is true, and their items
           show as icons in the rail). */}
        <SidebarGroup className="mt-3">
          <button
            type="button"
            onClick={() => setAdvancedOpen(o => !o)}
            className="flex items-center gap-1.5 px-2 py-1.5 text-xs uppercase tracking-widest text-sidebar-foreground/60 hover:text-sidebar-foreground transition-colors w-full"
            data-testid="sidebar-advanced-toggle"
            aria-expanded={advancedOpen}
          >
            {advancedOpen ? <ChevronDown className="w-3.5 h-3.5" /> : <ChevronRight className="w-3.5 h-3.5" />}
            <Settings2 className="w-3.5 h-3.5" />
            <span className="font-semibold">Advanced Settings</span>
          </button>
        </SidebarGroup>

        {showAdvanced && <>
        {/* TOOLS */}
        <SidebarGroup>
          <SidebarGroupLabel className="text-sidebar-foreground/50 text-xs uppercase tracking-widest">
            Tools
          </SidebarGroupLabel>
          <SidebarGroupContent>
            <SidebarMenu>{renderItems(toolItems)}</SidebarMenu>
          </SidebarGroupContent>
        </SidebarGroup>

        {/* ADMIN (admin-only) */}
        {user?.role === "admin" && (
          <SidebarGroup>
            <SidebarGroupLabel className="text-sidebar-foreground/50 text-xs uppercase tracking-widest">
              Admin
            </SidebarGroupLabel>
            <SidebarGroupContent>
              <SidebarMenu>{renderItems(adminItems)}</SidebarMenu>
            </SidebarGroupContent>
          </SidebarGroup>
        )}

        {/* VIEWER — read-only access to historical reports */}
        {user?.role === "viewer" && (
          <SidebarGroup>
            <SidebarGroupLabel className="text-sidebar-foreground/50 text-xs uppercase tracking-widest">
              Reports
            </SidebarGroupLabel>
            <SidebarGroupContent>
              <SidebarMenu>{renderItems(viewerItems)}</SidebarMenu>
            </SidebarGroupContent>
          </SidebarGroup>
        )}

        {/* HELP — always visible, above Integrations and Super Admin */}
        <SidebarGroup>
          <SidebarGroupLabel className="text-sidebar-foreground/50 text-xs uppercase tracking-widest">
            Help
          </SidebarGroupLabel>
          <SidebarGroupContent>
            <SidebarMenu>
              {renderItems([
                { title: "Help & Support",  url: "/support",  icon: LifeBuoy },
                { title: "Help Videos",     url: "/support",  icon: Video },
                { title: "Install App",     url: "/install",  icon: Smartphone },
              ])}
            </SidebarMenu>
          </SidebarGroupContent>
        </SidebarGroup>

        {/* INTEGRATIONS (admin only) */}
        {user?.role === "admin" && (
          <SidebarGroup>
            <SidebarGroupLabel className="text-sidebar-foreground/50 text-xs uppercase tracking-widest">
              Integrations
            </SidebarGroupLabel>
            <SidebarGroupContent>
              <SidebarMenu>{renderItems(integrationItems)}</SidebarMenu>
            </SidebarGroupContent>
          </SidebarGroup>
        )}

        {/* SUPER ADMIN (super-admin only) */}
        {user?.superAdmin && (
          <SidebarGroup>
            <SidebarGroupLabel className="text-sidebar-foreground/50 text-xs uppercase tracking-widest">
              Super Admin
            </SidebarGroupLabel>
            <SidebarGroupContent>
              <SidebarMenu>
                {renderItems([
                  { title: "SA Console", url: "/super-admin", icon: ShieldCheck },
                ])}
              </SidebarMenu>
            </SidebarGroupContent>
          </SidebarGroup>
        )}
        </>}
      </SidebarContent>

      <SidebarFooter className="p-4 border-t border-sidebar-border">
        <div className="flex items-center gap-2">
          <div className="w-7 h-7 rounded-full bg-sidebar-foreground/20 flex items-center justify-center text-xs font-bold text-sidebar-foreground flex-shrink-0">
            {initials}
          </div>
          <div className="flex-1 min-w-0">
            <p className="text-xs font-medium text-sidebar-foreground truncate">{user?.name ?? "—"}</p>
            <p className="text-xs text-sidebar-foreground/50 truncate">{roleLabel}</p>
          </div>
          <button
            onClick={logout}
            title="Sign out"
            className="ml-auto p-1.5 rounded hover:bg-sidebar-foreground/10 text-sidebar-foreground/50 hover:text-sidebar-foreground transition-colors flex-shrink-0"
          >
            <LogOut className="w-3.5 h-3.5" />
          </button>
        </div>
      </SidebarFooter>
    </Sidebar>
  );
}
